### ISSUE TITLE
Missing node types

### ISSUE THREAD

**Issue by Janther** [prettier-solidity/prettier-plugin-solidity#276]
Given the last few issues I started reviewing what we were missing from the list of node types of the parser.

According to solidity parsers [node list](https://github.com/solidity-parser/parser/blob/9093db3844327304f6a4bf6266405fbd4c81b06b/index.d.ts#L17) we are still missing these nodes:

- [ ] AssemblyFunctionReturns
- [x] AssemblyItem
- [x] AssemblyLiteral
- [x] AssemblyStackAssignment
- [x] Break
- [x] Continue
- [x] IdentifierList
- [x] PragmaName
- [x] PragmaValue
- [x] StateMutability
- [x] StorageLocation
- [ ] SubAssembly

In the same review I discovered that the list doesn't include these nodes that we do have:

- [x] CatchClause
- [x] IndexRangeAccess
- [x] NewExpression
- [x] TryStatement

@fvictorio could you do a cleanup of that list and let us know which node we do need to implement?

**Comment by marcusnewton** [comment]
I'm running into the following error:
```
Error: Unknown type: "Continue"
```

due to having `continue` in an `assembly` block. Is this getting addressed at some point?

**Comment by fvictorio** [comment]
@marcusnewton thanks, I opened https://github.com/prettier-solidity/prettier-plugin-solidity/issues/699 to track that issue.

**Comment by fvictorio** [comment]
@Janther I believe we support all nodes now (or we will, after merging #750). I'd say we close this one, and then open new issues if we missed some node.

**Comment by Janther** [comment]
Ok @fvictorio I did a review of this and we are still missing `AssemblyFunctionReturns` and `SubAssembly`.

I'll do a quick check and see what specifically these nodes are and implement them in our printers. If they are unused, you could just clean up these 2 in the parser.

**Comment by fvictorio** [comment]
Thank you @Janther, I checked and the `SubAssembly` node is not used at all. The `AssemblyFunctionReturns` is used in the ANTLR grammar, but abstracted by the parser, so that node doesn't make sense in `ast-types.ts` either and I removed it.
